import com.github.os72.protocjar.Protoc;
import com.google.protobuf.DescriptorProtos;
import com.google.protobuf.Descriptors;
import com.google.protobuf.DynamicMessage;
import com.google.protobuf.util.JsonFormat;

import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Protobuf decoding support: load descriptor sets and decode binary to JSON.
 */
public final class DumpBinaryProtobuf {

    private DumpBinaryProtobuf() {}

    /**
     * Load descriptors from a .desc or .proto file.
     * For .proto files, compiles at runtime using protoc-jar.
     *
     * @param path path to .desc or .proto file
     * @return list of message descriptors
     */
    public static List<Descriptors.Descriptor> loadFromPath(Path path) throws IOException {
        if (path == null || !Files.isRegularFile(path)) {
            throw new IOException("File not found: " + path);
        }
        String name = path.getFileName().toString().toLowerCase();
        if (name.endsWith(".proto")) {
            return loadFromProtoFile(path);
        }
        return loadDescriptorSet(path);
    }

    /**
     * Load a descriptor set from a .desc file (generated by protoc --descriptor_set_out).
     *
     * @param descPath path to the .desc file
     * @return list of message descriptors from all files in the set
     */
    public static List<Descriptors.Descriptor> loadDescriptorSet(Path descPath) throws IOException {
        if (descPath == null || !Files.isRegularFile(descPath)) {
            throw new IOException("Descriptor file not found: " + descPath);
        }
        List<Descriptors.Descriptor> descriptors = new ArrayList<>();
        try (FileInputStream fis = new FileInputStream(descPath.toFile())) {
            DescriptorProtos.FileDescriptorSet set = DescriptorProtos.FileDescriptorSet.parseFrom(fis);
            for (DescriptorProtos.FileDescriptorProto fileProto : set.getFileList()) {
                Descriptors.FileDescriptor fileDesc = Descriptors.FileDescriptor.buildFrom(
                        fileProto, new Descriptors.FileDescriptor[0], false);
                collectMessageDescriptors(fileDesc.getMessageTypes(), descriptors);
            }
        } catch (Descriptors.DescriptorValidationException e) {
            throw new IOException("Invalid descriptor: " + e.getMessage(), e);
        }
        return descriptors;
    }

    /**
     * Compile a .proto file at runtime and load descriptors.
     */
    public static List<Descriptors.Descriptor> loadFromProtoFile(Path protoPath) throws IOException {
        Path parentDir = protoPath.getParent();
        if (parentDir == null) parentDir = Path.of(".");
        Path tempDesc = Files.createTempFile("dump-binary-proto", ".desc");
        try {
            String[] args = {
                    "-I" + parentDir.toAbsolutePath(),
                    "--descriptor_set_out=" + tempDesc.toAbsolutePath(),
                    protoPath.toAbsolutePath().toString()
            };
            int exit;
            try {
                exit = Protoc.runProtoc(args);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                throw new IOException("protoc interrupted", e);
            }
            if (exit != 0) {
                throw new IOException("protoc failed with exit code " + exit);
            }
            return loadDescriptorSet(tempDesc);
        } finally {
            Files.deleteIfExists(tempDesc);
        }
    }

    private static void collectMessageDescriptors(
            List<Descriptors.Descriptor> messageTypes, List<Descriptors.Descriptor> out) {
        for (Descriptors.Descriptor d : messageTypes) {
            out.add(d);
            collectMessageDescriptors(d.getNestedTypes(), out);
        }
    }

    /**
     * Find a message descriptor by name (simple or fully qualified).
     */
    public static Descriptors.Descriptor findMessageDescriptor(
            List<Descriptors.Descriptor> descriptors, String messageTypeName) {
        if (messageTypeName == null || messageTypeName.isBlank()) {
            return descriptors.isEmpty() ? null : descriptors.get(0);
        }
        String search = messageTypeName.trim();
        for (Descriptors.Descriptor d : descriptors) {
            if (d.getFullName().equals(search) || d.getName().equals(search)) {
                return d;
            }
        }
        return null;
    }

    /**
     * Decode protobuf binary to JSON string.
     *
     * @param bytes raw protobuf bytes
     * @param descriptor message descriptor to use
     * @return JSON string, or null on failure
     */
    public static String decodeToJson(byte[] bytes, Descriptors.Descriptor descriptor) {
        if (bytes == null || descriptor == null) return null;
        try {
            DynamicMessage message = DynamicMessage.parseFrom(descriptor, bytes);
            return JsonFormat.printer()
                    .includingDefaultValueFields()
                    .preservingProtoFieldNames()
                    .print(message);
        } catch (Exception e) {
            return null;
        }
    }
}
